export const BACKEND_DOMAIN = "http://localhost:8080";

export const UNIVERSITIES = [
  "Adana Alparslan Türkeş Bilim ve Teknoloji Üniversitesi",
  "Çukurova Üniversitesi",
  "Adıyaman Üniversitesi",
  "Afyon Kocatepe Üniversitesi",
  "Afyonkarahisar Sağlık Bilimleri Üniversitesi",
  "Ağrı İbrahim Çeçen Üniversitesi",
  "Aksaray Üniversitesi",
  "Amasya Üniversitesi",
  "Ankara Üniversitesi",
  "Ankara Hacı Bayram Veli Üniversitesi",
  "Ankara Sosyal Bilimler Üniversitesi",
  "Gazi Üniversitesi",
  "Hacettepe Üniversitesi",
  "Orta Doğu Teknik Üniversitesi",
  "Ankara Yıldırım Beyazıt Üniversitesi",
  "Ankara Bilim Üniversitesi",
  "Ankara Medipol Üniversitesi",
  "Atılım Üniversitesi",
  "Başkent Üniversitesi",
  "Çankaya Üniversitesi",
  "Bilkent Üniversitesi",
  "Lokman Hekim Üniversitesi",
  "Ostim Teknik Üniversitesi",
  "TED Üniversitesi",
  "TOBB Ekonomi ve Teknoloji Üniversitesi",
  "Ufuk Üniversitesi",
  "Türk Hava Kurumu Üniversitesi",
  "Yüksek İhtisas Üniversitesi",
  "Akdeniz Üniversitesi",
  "Alanya Alaaddin Keykubat Üniversitesi",
  "Alanya Üniversitesi",
  "Antalya Belek Üniversitesi",
  "Antalya Bilim Üniversitesi",
  "Ardahan Üniversitesi",
  "Artvin Çoruh Üniversitesi",
  "Aydın Adnan Menderes Üniversitesi",
  "Balıkesir Üniversitesi",
  "Bandırma Onyedi Eylül Üniversitesi",
  "Bartın Üniversitesi",
  "Batman Üniversitesi",
  "Bayburt Üniversitesi",
  "Bilecik Şeyh Edebali Üniversitesi",
  "Bingöl Üniversitesi",
  "Bitlis Eren Üniversitesi",
  "Bolu Abant İzzet Baysal Üniversitesi",
  "Burdur Mehmet Akif Ersoy Üniversitesi",
  "Bursa Teknik Üniversitesi",
  "Bursa Uludağ Üniversitesi",
  "Mudanya Üniversitesi",
  "Çanakkale Onsekiz Mart Üniversitesi",
  "Çankırı Karatekin Üniversitesi",
  "Hitit Üniversitesi",
  "Pamukkale Üniversitesi",
  "Dicle Üniversitesi",
  "Düzce Üniversitesi",
  "Trakya Üniversitesi",
  "Fırat Üniversitesi",
  "Erzincan Binali Yıldırım Üniversitesi",
  "Atatürk Üniversitesi",
  "Erzurum Teknik Üniversitesi",
  "Anadolu Üniversitesi",
  "Eskişehir Osmangazi Üniversitesi",
  "Eskişehir Teknik Üniversitesi",
  "Gaziantep Üniversitesi",
  "Orta Doğu Teknik Üniversitesi",
  "Gaziantep İslam Bilim ve Teknoloji Üniversitesi",
  "Hasan Kalyoncu Üniversitesi",
  "Sanko Üniversitesi",
  "Giresun Üniversitesi",
  "Gümüşhane Üniversitesi",
  "Hakkari Üniversitesi",
  "İskenderun Teknik Üniversitesi",
  "Hatay Mustafa Kemal Üniversitesi",
  "Iğdır Üniversitesi",
  "Süleyman Demirel Üniversitesi",
  "Isparta Uygulamalı Bilimler Üniversitesi",
  "Boğaziçi Üniversitesi",
  "Galatasaray Üniversitesi",
  "İstanbul Medeniyet Üniversitesi",
  "İstanbul Teknik Üniversitesi",
  "İstanbul Üniversitesi",
  "İstanbul Üniversitesi-Cerrahpaşa",
  "Marmara Üniversitesi",
  "Milli Savunma Üniversitesi",
  "Mimar Sinan Güzel Sanatlar Üniversitesi",
  "Türk-Alman Üniversitesi",
  "Türk-Japon Bilim ve Teknoloji Üniversitesi",
  "Sağlık Bilimleri Üniversitesi",
  "Yıldız Teknik Üniversitesi",
  "Acıbadem Üniversitesi",
  "Altınbaş Üniversitesi",
  "Bahçeşehir Üniversitesi",
  "Beykoz Üniversitesi",
  "Bezmialem Vakıf Üniversitesi",
  "Biruni Üniversitesi",
  "Demiroğlu Bilim Üniversitesi",
  "Doğuş Üniversitesi",
  "Fatih Sultan Mehmet Üniversitesi",
  "Fenerbahçe Üniversitesi",
  "Haliç Üniversitesi",
  "Işık Üniversitesi",
  "İbn Haldun Üniversitesi",
  "İstanbul 29 Mayıs Üniversitesi",
  "İstanbul Arel Üniversitesi",
  "İstanbul Atlas Üniversitesi",
  "İstanbul Aydın Üniversitesi",
  "İstanbul Beykent Üniversitesi",
  "İstanbul Bilgi Üniversitesi",
  "İstanbul Esenyurt Üniversitesi",
  "İstanbul Galata Üniversitesi",
  "İstanbul Gedik Üniversitesi",
  "İstanbul Gelişim Üniversitesi",
  "İstanbul Kent Üniversitesi",
  "İstanbul Kültür Üniversitesi",
  "İstanbul Medipol Üniversitesi",
  "İstanbul Nişantaşı Üniversitesi",
  "İstanbul Okan Üniversitesi",
  "İstanbul Rumeli Üniversitesi",
  "İstanbul Sabahattin Zaim Üniversitesi",
  "İstanbul Sağlık ve Teknoloji Üniversitesi",
  "İstanbul Ticaret Üniversitesi",
  "İstanbul Topkapı Üniversitesi",
  "İstanbul Yeni Yüzyıl Üniversitesi",
  "İstinye Üniversitesi",
  "Kadir Has Üniversitesi",
  "Koç Üniversitesi",
  "Maltepe Üniversitesi",
  "MEF Üniversitesi",
  "Özyeğin Üniversitesi",
  "Piri Reis Üniversitesi",
  "Sabancı Üniversitesi",
  "Üsküdar Üniversitesi",
  "Yeditepe Üniversitesi",
  "Dokuz Eylül Üniversitesi",
  "Ege Üniversitesi",
  "İzmir Kâtip Çelebi Üniversitesi",
  "İzmir Bakırçay Üniversitesi",
  "İzmir Demokrasi Üniversitesi",
  "İzmir Ekonomi Üniversitesi",
  "İzmir Tınaztepe Üniversitesi",
  "Yaşar Üniversitesi",
  "Kahramanmaraş Sütçü İmam Üniversitesi",
  "Kahramanmaraş İstiklal Üniversitesi",
  "Karabük Üniversitesi",
  "Karamanoğlu Mehmetbey Üniversitesi",
  "Kafkas Üniversitesi (Türkiye)",
  "Kastamonu Üniversitesi",
  "Abdullah Gül Üniversitesi",
  "Erciyes Üniversitesi",
  "Kayseri Üniversitesi",
  "Nuh Naci Yazgan Üniversitesi",
  "Kırıkkale Üniversitesi",
  "Kırklareli Üniversitesi",
  "Kırşehir Ahi Evran Üniversitesi",
  "Kilis 7 Aralık Üniversitesi",
  "Gebze Teknik Üniversitesi",
  "Kocaeli Üniversitesi",
  "Kocaeli Sağlık ve Teknoloji Üniversitesi",
  "Konya Teknik Üniversitesi",
  "Necmettin Erbakan Üniversitesi",
  "Selçuk Üniversitesi",
  "Konya Gıda ve Tarım Üniversitesi",
  "KTO Karatay Üniversitesi",
  "Kütahya Dumlupınar Üniversitesi",
  "Kütahya Sağlık Bilimleri Üniversitesi",
  "İnönü Üniversitesi",
  "Malatya Turgut Özal Üniversitesi",
  "Manisa Celal Bayar Üniversitesi",
  "Mardin Artuklu Üniversitesi",
  "Mersin Üniversitesi",
  "Tarsus Üniversitesi",
  "Çağ Üniversitesi",
  "Toros Üniversitesi",
  "Muğla Sıtkı Koçman Üniversitesi",
  "Muş Alparslan Üniversitesi",
  "Nevşehir Hacı Bektaş Veli Üniversitesi",
  "Kapadokya Üniversitesi",
  "Niğde Ömer Halisdemir Üniversitesi",
  "Ordu Üniversitesi",
  "Osmaniye Korkut Ata Üniversitesi",
  "Recep Tayyip Erdoğan Üniversitesi",
  "Sakarya Üniversitesi",
  "İstanbul Teknik Üniversitesi",
  "Sakarya Uygulamalı Bilimler Üniversitesi",
  "Ondokuz Mayıs Üniversitesi",
  "Samsun Üniversitesi",
  "Siirt Üniversitesi",
  "Sinop Üniversitesi",
  "Sivas Cumhuriyet Üniversitesi",
  "Sivas Bilim ve Teknoloji Üniversitesi",
  "Harran Üniversitesi",
  "Şırnak Üniversitesi",
  "Tekirdağ Namık Kemal Üniversitesi",
  "Tokat Gaziosmanpaşa Üniversitesi",
  "Karadeniz Teknik Üniversitesi",
  "Trabzon Üniversitesi",
  "Avrasya Üniversitesi",
  "Munzur Üniversitesi",
  "Uşak Üniversitesi",
  "Van Yüzüncü Yıl Üniversitesi",
  "Yalova Üniversitesi",
  "Yozgat Bozok Üniversitesi",
  "Zonguldak Bülent Ecevit Üniversitesi",
];

export const LANGUAGE_DETAILS = {
  c: { name: "C", extension: "c" },
  cpp: { name: "C++", extension: "cpp" },
  csharp: { name: "C#", extension: "cs" },
  lua: { name: "Lua", extension: "lua" },
  python: { name: "Python", extension: "py" },
  java: { name: "Java", extension: "java" },
  javascript: { name: "Javascript", extension: "js" },
};

export const COMMENT_LINES = {
  c: "//",
  cpp: "//",
  csharp: "//",
  lua: "--",
  python: "#",
  java: "//",
  javascript: "//",
};
